### ISSUE TITLE
最终修改

### ISSUE THREAD

**Issue by lock0** [mangoeasy/hk-mobile#3]
1、banner自动翻页+滑动
2、订单选择页--手机型号文字部分后面跟颜色的image
3、黄色框---库存+最新订单这块DIV 做成用户滑动手机后始终置顶
4、iphone6广告图片替换成一张，图片已发送至你gmail邮箱
5、select page更改文字 "恭喜你！获得抢购资格"改成”现在下单可免费获取：价值198元的剪卡器、高清膜、手机壳套装“
6、顶部蓝色区域高度稍微调窄些

**Comment by iamike** [comment]
1、banner自动翻页+滑动 
DONE
2、订单选择页--手机型号文字部分后面跟颜色的image
DONE
3、黄色框---库存+最新订单这块DIV 做成用户滑动手机后始终置顶
DONE
4、iphone6广告图片替换成一张，图片已发送至你gmail邮箱
DONE
5、select page更改文字 "恭喜你！获得抢购资格"改成”现在下单可免费获取：价值198元的剪卡器、高清膜、手机壳套装“
DONE
6、顶部蓝色区域高度稍微调窄些
DONE
